import React from 'react';

import './CurrentUser.styles.css'

const CurrentUser = () => {
    return (
        <div className="CurrentUser">
          
             <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
            <div>lorem106</div>
        </div>
    )
}

export default CurrentUser;